name: ${project.name}
version: ${project.version}
description: "Fix the annoying invisible player bug."
main: net.mystalion.rightpacketorder.RightPacketOrder
authors: [Paulomart]
depend: [ProtocolLib]
